# This file is managed by Copier — do not delete it. It records the answers given
# when this project was generated and is required for `copier update` to work.
_commit: v1.0.6
_src_path: gh:fellnerd/datavault-dbt-boilerplate
author_name: Daniel Fellner, MSc
company_name: ppmc ag
database_name: datavault
github_org: fellnerd
hash_algorithm: SHA
include_example: false
include_infra: true
infra_location: switzerlandnorth
infra_sql_server_name: ppmcag-datavault
infra_storage_account_name: stdatavault001
infra_storage_container_name: stage-fs
mart_schema: mart
profile_name: datavault
project_name: datavault
schema_prefix: vault
staging_schema: stg
warehouse_server_example: ppmcag-datavault.database.windows.net
