{#
    Link Satellite: sat_kunde_adresse
    Parent Link: link_kunde_adresse
    Payload: AddressType, ModifiedDate
    Source: adworks_kunde_adresse
    
    A Link Satellite holds the descriptive attributes of a Link relationship.
    The Link Hash Key is the primary key.
    
    Example: AddressType describes the customer-address relationship
    
    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_link_satellites/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=[
        "{{ create_hash_index('hk_link_kunde_adresse') }}",
        "{{ update_satellite_current_flag(this, 'hk_link_kunde_adresse') }}"
    ]
) }}

{%- set yaml_metadata -%}
source_model: "adworks_kunde_adresse"
src_pk: "hk_link_kunde_adresse"
src_hashdiff: 
  source_column: "hd_kunde_adresse"
  alias: "hashdiff"
src_payload: 
    - "addresstype"
    - "modifieddate"
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
