{#
    Satellite: sat_kunde
    Parent Hub: hub_kunde
    Source: adworks_kunde
    Payload: NameStyle, Title, FirstName, MiddleName, LastName, Suffix, CompanyName, SalesPerson, EmailAddress, Phone, PasswordHash, PasswordSalt, ModifiedDate
    
    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_satellites/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=[
        "{{ create_hash_index('hk_kunde') }}",
        "{{ update_satellite_current_flag(this, 'hk_kunde') }}"
    ]
) }}

{%- set yaml_metadata -%}
source_model: "adworks_kunde"
src_pk: "hk_kunde"
src_hashdiff: 
  source_column: "hd_kunde"
  alias: "hashdiff"
src_payload: 
    - "namestyle"
    - "title"
    - "firstname"
    - "middlename"
    - "lastname"
    - "suffix"
    - "companyname"
    - "salesperson"
    - "emailaddress"
    - "phone"
    - "passwordhash"
    - "passwordsalt"
    - "modifieddate"
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
