{#
    Dependent Child Satellite: sat_verkauf_detail_dc
    Parent Link: link_verkauf_detail
    DCK Columns: SalesOrderDetailID
    Payload: SalesOrderDetailID, OrderQty, UnitPrice, UnitPriceDiscount, LineTotal, ModifiedDate
    Source: adworks_verkauf_detail
    
    A Dependent Child Satellite tracks changes to link relationships
    that require additional keys (DCKs) for uniqueness.
    The Link Hash Key includes DCK columns (calculated in staging).
    
    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_dep_child/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=[
        "{{ create_hash_index('hk_link_verkauf_detail') }}",
        "{{ update_satellite_current_flag(this, 'hk_link_verkauf_detail') }}"
    ]
) }}

{%- set yaml_metadata -%}
source_model: "adworks_verkauf_detail"
src_pk: "hk_link_verkauf_detail"
src_hashdiff: 
  source_column: "hd_verkauf_detail_dc"
  alias: "hashdiff"
src_payload: 
    - "salesorderdetailid"
    - "orderqty"
    - "unitprice"
    - "unitpricediscount"
    - "linetotal"
    - "modifieddate"
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
