{#
    Split-Satellite: sat_produkt
    Parent Hub: hub_produkt (existing hub in adworks)
    Source: adworks_produkt
    Payload: Name, ProductNumber, Size, Weight, ProductModelID, ModifiedDate
    
    This is a Split-Satellite that shares its Hub with other satellites.
    It uses the existing hub's hash key (hk_produkt) as its primary key.
    
    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_satellites/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=[
        "{{ create_hash_index('hk_produkt') }}",
        "{{ update_satellite_current_flag(this, 'hk_produkt') }}"
    ]
) }}

{%- set yaml_metadata -%}
source_model: "adworks_produkt"
src_pk: "hk_produkt"
src_hashdiff: 
  source_column: "hd_produkt"
  alias: "hashdiff"
src_payload: 
    - "name"
    - "productnumber"
    - "size"
    - "weight"
    - "productmodelid"
    - "modifieddate"
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
