{#
    Satellite: sat_verkauf
    Parent Hub: hub_verkauf
    Source: adworks_verkauf
    Payload: RevisionNumber, OrderDate, DueDate, ShipDate, Status, OnlineOrderFlag, SalesOrderNumber, PurchaseOrderNumber, AccountNumber, ShipMethod, CreditCardApprovalCode, SubTotal, TaxAmt, Freight, TotalDue, Comment, ModifiedDate
    
    Generated by Entity Designer using automate_dv.sat macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_satellites/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=[
        "{{ create_hash_index('hk_verkauf') }}",
        "{{ update_satellite_current_flag(this, 'hk_verkauf') }}"
    ]
) }}

{%- set yaml_metadata -%}
source_model: "adworks_verkauf"
src_pk: "hk_verkauf"
src_hashdiff: 
  source_column: "hd_verkauf"
  alias: "hashdiff"
src_payload: 
    - "revisionnumber"
    - "orderdate"
    - "duedate"
    - "shipdate"
    - "status"
    - "onlineorderflag"
    - "salesordernumber"
    - "purchaseordernumber"
    - "accountnumber"
    - "shipmethod"
    - "creditcardapprovalcode"
    - "subtotal"
    - "taxamt"
    - "freight"
    - "totaldue"
    - "comment"
    - "modifieddate"
src_eff: "dss_load_date"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(
    src_pk=metadata_dict["src_pk"],
    src_hashdiff=metadata_dict["src_hashdiff"],
    src_payload=metadata_dict["src_payload"],
    src_eff=metadata_dict["src_eff"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
