{#
    DC Link (Dependent Child): link_verkauf_detail
    Connects: hub_verkauf, hub_produkt
    DCK Columns: SalesOrderDetailID
    Source: adworks_verkauf_detail
    
    A Dependent Child Link connects multiple Hubs but represents
    an entity that has no own Business Key (e.g., order line items).
    
    The Link Hash Key = HASH(all FKs + DCK columns) - calculated in staging.
    The actual DCK values are stored in the DC Satellite.
    
    Generated by Entity Designer using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=[
        "{{ create_hash_index('hk_link_verkauf_detail') }}"
    ]
) }}

{%- set yaml_metadata -%}
source_model: "adworks_verkauf_detail"
src_pk: "hk_link_verkauf_detail"
src_fk: 
    - "hk_verkauf"
    - "hk_produkt"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
