{#
    Pure Link (Intersection Table): link_kunde_adresse
    Connects: hub_kunde, hub_adresse
    Source: adworks_kunde_adresse
    
    A Pure Link Entity represents an intersection/bridge table
    that connects multiple Hubs without having its own identity.
    The combined FK hash keys form the Link Hash Key.
    
    Example: customeraddress connects customer and address
    
    Generated by Entity Designer using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=[
        "{{ create_hash_index('hk_link_kunde_adresse') }}"
    ]
) }}

{%- set yaml_metadata -%}
source_model: "adworks_kunde_adresse"
src_pk: "hk_link_kunde_adresse"
src_fk: 
    - "hk_kunde"
    - "hk_adresse"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
