{#
    Link: link_verkauf_kunde
    Source Hub: hub_verkauf
    Target Hub: adworks.hub_kunde
    Driving Key: CustomerID
    Source: adworks_verkauf
    
    Note: In automate_dv, links don't store payload columns.
    DCK columns are only used for the link hash calculation in staging.
    The actual DCK values are stored in the DC Satellite.
    
    Generated by Entity Designer using automate_dv.link macro
    @see https://automate-dv.readthedocs.io/en/latest/tutorial/tut_links/
#}

{{ config(
    materialized='incremental',
    as_columnstore=false,
    post_hook=["{{ create_hash_index('hk_link_verkauf_kunde') }}"]
) }}

{%- set yaml_metadata -%}
source_model: "adworks_verkauf"
src_pk: "hk_link_verkauf_kunde"
src_fk: 
    - "hk_verkauf"
    - "hk_kunde"
src_ldts: "dss_load_date"
src_source: "dss_record_source"
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.link(
    src_pk=metadata_dict["src_pk"],
    src_fk=metadata_dict["src_fk"],
    src_ldts=metadata_dict["src_ldts"],
    src_source=metadata_dict["src_source"],
    source_model=metadata_dict["source_model"]
) }}
